module.exports = {
	SKU_NOT_FOUND: 'SKU_NOT_FOUND',
	PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
	ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
	NOT_AUTHORIZED: 'NOT_AUTHORIZED',
	INVALID_INPUT: 'INVALID_INPUT',
	INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
	DUPLICATE_BARCODE: 'DUPLICATE_BARCODE',
	ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
	SERVER_ERROR: 'SERVER_ERROR',
};
